baseUrl: "https://jenkins.mono-project.com/view/All/"
url:
  searchPattern: ""
  replacement: ""
credits:
jiraBaseUrl:
jiraTaskRegEx: "TBBT-\\d{1,4}"
swimlanes:
  Mainline: "^(master).*"
  Features: "^(feature).*"